require('../angular/angular.min.js');
require('../angular/angular-sanitize.min.js');
require('../angular/angular-resource.min.js');
require('../angular/angular-animate.min.js');
require('../angular/angular-tree-control.js');
require('../angular/angular-ui-router.min.js');
require('../angular/angular-locale_zh-cn.js');
require('../lazy-image/lazy-image.min.js');
require('../bindonce.min.js');
require('../security.js');
require('../ng.element.js');

require('./index.scss');
require('./accordion');
require('./crumb');
require('./tooltip');
require('./login');
require('./pagination');
require('./tab');
require('./scroll');
require('./imgerror');
require('./search');
require('./anchor');
require('./dialog');
require('./loadScript');
require('./ueditor/angular-ueditor');

require('./switch');
require('./alert');
require('./rate');
require('./checkbox');
require('./transfer');
require('./autocomplete');
require('./pdf');
require('./upload');
require('./carousel');
require('./datepicker');

angular.module('jmui', [
    'jmui.carousel',
    'jmui.accordion',
    'jmui.crumbs',
    'jmui.tooltip',
    'jmui.login',
    'jmui.pagination',
    'jmui.tab',
    'jmui.scroll',
    'jmui.imgerror',
    'jmui.search',
    'jmui.AnchorSmoothScroll',
    'jmui.dialog',
    'jmui.loadScript',
    'jmui.switch',
    'jmui.alert',
    'jmui.rate',
    'jmui.checkbox',
    'jmui.transfer',
    'jmui.autoComplete',
    'jmui.pdf',
    'jmui.fineUploader',
    'ng.ueditor',
    'ui.bootstrap.datepicker'
]).value('version', '0.1');