var app = require('./app.js');
require('../css/bootstrap/css/bootstrap.min.css');
require('../dep/ng-lazy-image/lazy-image-style.css');
require('../css/style.css');
require('../css/postcss-demo.css');
require('../css/less-demo.less');
require('../css/sass-demo.scss');
require('../js/directive/directive.js');
require('../js/filter/filter.js');
require('../js/service/service.js');
require('../js/service/dialogs.js');
require('../js/controller/publicCtrl.js');
// require('controller/homeCtrl');
