var app = require('./app.js')
require('../css/bootstrap/css/bootstrap.min.css')
require('../css/style.css')
require('../css/icon.css')
require('../js/directive/directive.js')
require('../js/service/service.js')
require('../js/controller/publicCtrl.js')
// require('controller/homeCtrl')
